### PR TITLE
Add SQLiteConnection support

### PR DESCRIPTION
**Pull request by tgeorgel**
This PR adds support for the SQLiteConnection driver.

It should not bring breaking changes as it only add support for a previously unsupported driver.

One can run tests by setting `DB_CONNECTION=sqlite` in the `.env` file. No additional test were added as this PR intend to support the same features as the one already available for the PGSQL and MySQL drivers.

### CODE REVIEW

**Comment by xalaida** [comment]
@tgeorgel thanks for the PR. Could you please add a sqlite_test section to the github workflow? Just to make sure it runs with other actions.

**Comment by tgeorgel** [comment]
> @tgeorgel thanks for the PR. Could you please add a sqlite_test section to the github workflow? Just to make sure it runs with other actions.

I've added the workflow, I didn't notice them at the first place, my bad.

I have fails on some workflow, but I'm not sure why (it says categories table is missing). Any clue ?

**Comment by xalaida** [comment]
Some bug with the testing kit. It overrides the database connection name from specified in environment variables (which is "sqlite) to "testing"

**Comment by xalaida** [comment]
@tgeorgel thanks for the contribution

**Comment by tgeorgel** [comment]
> @tgeorgel thanks for the contribution

@xalaida thanks for the package ! 👏

**Pull request merged**
